L2 analityk biznesowy michal szlazak
MiloszMertka/pw-iwo-lab pull request #16
Opened 2024-03-15 10:03 UTC by Michal-Szlazak

Poprawione modele biznesowe

2024-03-15 12:43 UTC, MiloszMertka commented
@sekulas @StanislawMalinski 
Prosiłbym o waszą opinię na temat tych modeli. Według mnie pierwszy model jest trochę niezrozumiały, natomiast pozostałej wydają się być w porządku. Co do notacji to nie widzę błędów.

2024-03-15 12:45 UTC, MiloszMertka requested changes
Brakuje mi jeszcze opisów tych diagramów w markdown (mogą być skopiowane z SWZ wg mnie)

2024-03-15 16:47 UTC, sekulas commented
Ogółem to nie mam doświadczenia z diagramami aktywności z basenami, ale nie wiem czy przypadkiem pod względem składniowym nie powinno być (przykład 7. Komunikat o niemożności wystawienia opinii to chyba nie jest aktywność, nie wiem czy nie powinno być np. ,,zakomunikowanie niemożności wystawienia opinii", ale Lesiowi pewnie bedzie rybka)
Ale jeśli chodzi spójność z SWZ to:
7. Nie jestem pewien co to znaczy poprawność formularza i po co miałaby być ona weryfikowana - my sprawdzamy czy tam są przekleństwa, czy jakieś inne dane? - dane opinii nie są w słowniku, więc chyba trzeba uzgodnić z klientem. Ktoś może to gdzieś zanotować w sumie jakiś docs z pytankami do klientów.
10. Nie mamy określonego co się dzieje, gdy klient odmówi zmiany propozycji zmaówienia. Nie mamy określonego znaczenia złożenie zmaówienia - czy jest ono już opłacone czy nie, bo jeśli tak to chyba trzeba mu sianko zwrócić jakoś. A z diagramu wynika jakby już było opłacone. (w słowniku mamy określone to jako informacje o żądanej usłudze, wygląda jakby nie było opłacone)
Wszystko inne wygląda superancko. Good job!

2024-03-15 16:53 UTC, sekulas commented
Poprawka, sprawdziłem dokładniej i cały mój komentarz do 10 nie jest potrzebny - jest to już zmaówienie opłacone, na podstawie diagramu nr 3, który powstanie, ale w takim wypadku trzeba uzgodnić jakąś formę rekompensaty dla klienta, który nie otrzyma zamówienia i zrezygnuej ze zmiany terminu lub zamówienia.

2024-03-15 22:15 UTC, sekulas approved these changes

2024-03-16 08:09 UTC, MiloszMertka approved these changes
Wszystkie uwagi ode mnie zastosowane więc akceptuję

2024-03-17 07:30 UTC, StanislawMalinski commented
Dzień dobry,
wg słynnej maksymy "minimalna liczba znaków i minimalna liczba lini" uprościłbym diagram numer 9. Można zauważyć że środkowa odnoga w fork'u bezpośrednio zawsze przechodzi do końca procesu, odnoga ta więc jest niepotrzebna. Dzięki tej modyfikacji możemy również usunąć jednego merge node'a oraz jednego decision node'a.
(Po za tym fork zazwyczaj powinien być join'owany, ale ponieważ jesteś spójny w tej notacji nie mam z tym problemu.)

2024-03-17 18:22 UTC, Michal-Szlazak commented
Usunąłem środkową odnogę i zbędnego merge'a i decision node'a. @StanislawMalinski

2024-03-18 05:26 UTC, StanislawMalinski approved these changes
Cudo, dobra robota

2024-03-18 06:25 UTC, merged