PB 1-3
MiloszMertka/pw-iwo-lab pull request #17
Opened 2024-03-15 11:39 UTC by nijug

2024-03-15 12:47 UTC, MiloszMertka requested changes
Prosiłbym o zastosowanie tożsamej konwencji co @Michal-Szlazak tj. Tory z rolami zamiast umieszczania ról w nawiasach kwadratowych oraz podobny schemat przepływu sterowania i nazewnictwa.

2024-03-16 15:10 UTC, nijug commented
@MiloszMertka poprawione

2024-03-17 13:49 UTC, StanislawMalinski commented
Od strony notacyjnej:
Rejestracja dostawcy w systemie:
dodanie merge node'a kiedy więcej niż jedna strzałka wchodzi do akcji. W tym przypadku potrzebujemy tego przed "Połączenie z API dostawcy"
Popraw "Powiadomienie o udanym połączeniu" tak żeby napis mieścił się w jednym okienku
Rejestracja klienta w systemie:
Klient nie wchodzi w interakcje z systemem XD. Weź dodaj przesyłanie jakiś informacji do systemu. Uwzględnij proces weryfikacji. Do notacji nie mam uwag.
Założenie zamówienia przez klienta:
1. Klient nie wchodzi w interakcje z API dostawcy tylko z systemem, który budujemy.
2. Merge node - przed "Przeglądanie dostępnych posiłków. (pamiętaj, żeby mergować i przejście i od decyzji "czy klient finalizuje zamówienie i od powiadomienia o braku posiłków)
3. Merge node - przed "Przejście do strony płatności" 
4. Usunięcie "Tak" oraz "Nie" z nad powiadomień o nie/udanej transakcji.
5. Jakieś losowe "Nie" lata sobie również przy "Powiadomieniu o braku posiłków"
6. Literówka w "Dodanie wybranych posiłków do **korzyka**"

2024-03-17 15:58 UTC, nijug commented
@StanislawMalinski poprawione

2024-03-17 22:35 UTC, MiloszMertka approved these changes
Według mnie jest w porządku. Zatwierdzam

2024-03-18 05:24 UTC, StanislawMalinski approved these changes
Teraz elegancko, dobra robota

2024-03-18 07:32 UTC, sekulas commented
Dobra robota!
> Do przegadania z klientem - jakie **dane osobowe** chce zbierać.

2024-03-18 07:32 UTC, sekulas approved these changes

2024-03-18 08:16 UTC, merged