L2 Analityk biznesowy Sebastian Pietrykowski
MiloszMertka/pw-iwo-lab pull request #21
Opened 2024-03-16 12:49 UTC by sebastian-pietrykowski

2024-03-17 08:16 UTC, StanislawMalinski commented
Siemano,
więc trochę będziesz musiał poprawić.
join (czyli belka) oczekuje na dwa żetony i nie pójdzie dalej dopóki obu nie dostanie, dlatego zamień je na merge node'a.
diagram numer 4, eee no ja tak nie może być XD. Żeby to dało się to w pojedyńczych kawałkach zjeść wydziel większe segmenty takie jak wprowadzenie kodu rabatowego, wystawienie faktury do mniejszych diagramów, tak żeby jeden diagram dało się przeczytać bez przewijania.

2024-03-17 12:01 UTC, sebastian-pietrykowski commented
@StanislawMalinski Poprawione

2024-03-17 22:39 UTC, MiloszMertka requested changes
Według mnie jest zbyt technicznie. Procesy biznesowe jednak nie powinny za bardzo wnikać w implementację.

2024-03-17 22:59 UTC, sekulas commented
Co do zgodności z SWZ to nie mam zastrzeżeń, to co trzeba uzgodnić z klientem to:
4. **filtry oferty** - czym są i jak mają wyglądać. **forma dostawy** - jakie mamy formy dostawy. **sposoby płatności** - jakie mają być w systemie
Postaram się we wtorek dopytać o powyższe i zanotować.

2024-03-17 22:59 UTC, sekulas approved these changes

2024-03-18 05:30 UTC, StanislawMalinski approved these changes
Wygląda to dużo lepiej.

2024-03-18 20:06 UTC, merged